skip_tags: true
clone_depth: 1
pull_requests:
  do_not_increment_build_number: true

version: '{branch} build {build}'
image: Visual Studio 2017

clone_folder: C:\projects\librime-lua

environment:
  BOOST_ROOT: C:\Libraries\boost_1_69_0
  CL: /Zc:threadSafeInit-
  RIME_DIR: C:\projects\librime

cache:
  - C:\projects\librime\thirdparty.cached -> appveyor.yml
  - C:\projects\librime\thirdparty\bin -> appveyor.yml
  - C:\projects\librime\thirdparty\include -> appveyor.yml
  - C:\projects\librime\thirdparty\lib -> appveyor.yml
  - C:\projects\librime\thirdparty\share -> appveyor.yml
  - C:\Libraries\boost_1_69_0\stage -> appveyor.yml

init:
  - git --version
  - cmake --version
  - git config --global core.autocrlf true
  - git clone https://github.com/rime/librime.git --depth=1 --recurse-submodules %RIME_DIR%

install:
  - .\appveyor.rime-install.bat

build_script:
  - cd %RIME_DIR%
  - .\build.bat test

after_build:
  - cd %RIME_DIR%
  - 7z a ..\librime-lua\rime.zip dist thirdparty\bin thirdparty\share
  - dir dist /s

before_test:
  - cd %RIME_DIR%
  - copy /y dist\lib\rime.dll build\test

test_script:
  - cd %RIME_DIR%\build\test
  - .\Release\rime_test.exe

artifacts:
  - path: rime.zip
    name: Binaries, includes and OpenCC data
